# Generated by Django 3.2.8 on 2021-10-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagforest', '0002_auto_20211024_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='tags',
            new_name='tag_set',
        ),
        migrations.AddField(
            model_name='tag',
            name='parent_set',
            field=models.ManyToManyField(related_name='child_set', related_query_name='child', to='tagforest.Tag'),
        ),
    ]
