# Generated by Django 3.2.8 on 2021-10-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagforest', '0003_auto_20211024_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
