# Generated by Django 3.2.8 on 2021-11-02 21:03

from django.conf import settings
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
            ('tagforest', '0006_auto_20211102_2102'),
            ]

    def set_default(apps, schema_editor):
        User = apps.get_model(settings.AUTH_USER_MODEL)
        Entry = apps.get_model('tagforest', 'Entry')
        Tag = apps.get_model('tagforest', 'Tag')
        default_user = User.objects.first()
        for entry in Entry.objects.all().iterator():
            entry.user = default_user
            entry.save()
        for tag in Tag.objects.all().iterator():
            tag.user = default_user
            tag.save()

    def set_default_reverse(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(set_default, set_default_reverse),
    ]
