# Generated by Django 3.2.8 on 2021-11-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagforest', '0009_entry_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='parent_set',
            field=models.ManyToManyField(blank=True, related_name='child_set', related_query_name='child', to='tagforest.Tag'),
        ),
    ]
