# Generated by Django 4.0.6 on 2023-02-13 14:43

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('tagforest', '0011_auto_20211103_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
