# Generated by Django 4.0.6 on 2023-02-13 14:43

from django.db import migrations

def convert_entry_to_tag(apps, schema_editor):
  Tag = apps.get_model('tagforest', 'Tag')
  Entry = apps.get_model('tagforest', 'Entry')

  for entry in Entry.objects.all():
    tag = Tag(name=entry.name, content=entry.content, user=entry.user)
    tag.save()
    for parent in entry.tag_set.all():
      tag.parent_set.add(parent)
    tag.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tagforest', '0012_auto_20230213_1443'),
    ]

    operations = [
        migrations.RunPython(convert_entry_to_tag, reverse_code=migrations.RunPython.noop),
    ]
