# Generated by Django 4.0.6 on 2023-02-13 14:43

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('tagforest', '0013_auto_20230213_1443'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
