# Generated by Django 4.0.6 on 2023-02-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagforest', '0014_auto_20230213_1443'),
    ]

    operations = [
    ]
