# Generated by Django 4.0.6 on 2023-02-13 16:19

from django.db import migrations

def add_default_category(apps, schema_editor):
  TagCategory = apps.get_model('tagforest', 'TagCategory')
  Tag = apps.get_model('tagforest', 'Tag')
  category = TagCategory(name="Artist")
  category_user_map = {}
  for tag in Tag.objects.all():
    if tag.user not in category_user_map:
      category = TagCategory(name="Artist", user=tag.user)
      category.save()
      category_user_map[tag.user] = category
    tag.category = category_user_map[tag.user]
    tag.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tagforest', '0018_tag_category'),
    ]

    operations = [
        migrations.RunPython(add_default_category, reverse_code=migrations.RunPython.noop),
    ]
