# Generated by Django 4.0.6 on 2023-02-13 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagforest', '0019_auto_20230213_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagforest.tagcategory'),
        ),
    ]
