# Generated by Django 4.0.6 on 2023-04-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagforest', '0020_alter_tag_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagcategory',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='color',
            field=models.CharField(default='ffffff', max_length=255),
        ),
    ]
