# Generated by Django 4.0.6 on 2023-04-16 21:25

from django.db import migrations

def add_default_tree(apps, schema_editor):
  Tree = apps.get_model('tagforest', 'Tree')
  Tag = apps.get_model('tagforest', 'Tag')
  TagCategory = apps.get_model('tagforest', 'TagCategory')
  tree_user_map = {}
  for tag in Tag.objects.all():
    if tag.user not in tree_user_map:
      tree = Tree(name="Default", user=tag.user)
      tree.save()
      tree_user_map[tag.user] = tree
    tag.tree = tree_user_map[tag.user]
    tag.save()
  for category in TagCategory.objects.all():
    if category.user not in tree_user_map:
      tree = Tree(name="Default", user=category.user)
      tree.save()
      tree_user_map[category.user] = tree
    category.tree = tree_user_map[category.user]
    category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tagforest', '0022_tree_tag_tree_tagcategory_tree'),
    ]

    operations = [
        migrations.RunPython(add_default_tree, reverse_code=migrations.RunPython.noop),
    ]
