# Generated by Django 4.0.6 on 2023-04-16 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagforest', '0023_auto_20230416_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagforest.tree'),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagforest.tree'),
        ),
    ]
