# Generated by Django 4.0.6 on 2023-04-16 21:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tagforest', '0024_alter_tag_tree_alter_tagcategory_tree'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'user', 'tree')},
        ),
        migrations.AlterUniqueTogether(
            name='tagcategory',
            unique_together={('name', 'user', 'tree')},
        ),
    ]
