# Generated by Django 4.0.6 on 2023-05-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagforest', '0026_tagcategory_show_in_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
